[package]
name = "online-tool"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
windows-sys = { version = "0.48", features = [
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging"
]}
crossterm = "0.28.1"
